### ISSUE TITLE
putPage issue when data plugin involved

### ISSUE THREAD

**Issue by roadrunnerjb** [gturri/dokuJClient#26]
Hi,
I'm using docujclient Version 3.8.0 in conjunction with my dokuwiki Release 2014-09-29d Hrun instance.
I've written a Windows script that uses dokujclient commandline putPage to insert new pages into the wiki.

There are 2 cases of content. With and without following sections containig blocks like this:

---- datatemplateentry beleg ----
template   : xx:tpl:beleg
nummer     : b16232
objekt     : ob:xx
beleg-typ  : DTYP:RE
beleg-dt   : 2016-12-27
beleg-jahr : 2016
kategorie  : 
partner    : PA:HW:diverse 
betrag     : 27.25
zahlbetrag : 27.25
lohnanteil : 
zahl-dt    : 2016-12-27
steuer     : X
----

When I put pages without such blocks everything works. When I put pages containing such blocks I get an error from the DokuJClient commandline. 

But when I copy the same text into the dokuwiki editor and save the page all works as expected.

So my question is, what is wrong doing this the dokuJClient xmlrpc way and how can I get this working.

Help is apreciated

Regards Joachim

**Comment by gturri** [comment]
Thank you for your feedback.

Could you please give me more info about the error you get from the dokujclient commandline?
When I try to reproduce the issue, I get `Unknown flag '-'.` . Are you getting the same error, or are you getting something else?

**Comment by roadrunnerjb** [comment]
Hi, thx for your quick answer. 

Do you have all needed plugins installed in your test Scenario ? may be that is the reason for the unknow flag ...

I can only see RC=1 in my script.
 
So I tried to isolate the commandline out of my script and run this in a cmd Shell. The only difference I see is that I must pipe the content from an intermediate file into the commandline whereelse in the script the content is provided via variable. And what surprise when I pipe the content the page is created.

Example (anonymized):

`C:\STICK\PortableApps\CommonFiles\Java\bin\java.exe  -jar \\ocr\appl\dokujclient\dokuJClient-3.8.0.jar -u username -p password --url https://mywiki..de/lib/exe/xmlrpc.php putPage  ablage:2017:b17027-re-testpage <\\ocr\appl\trace\ablage-2017-b17027-re-testpage.txt
`

So my Workaround will be to write the temp file out in the script and pipe it into dokuJClient. But still no idea what is wrong with using a variable (but seems not to be a dokuJClient issue ) ...
I'll come back to you when I implemented an tested this workaround

Regards Joachim

**Comment by roadrunnerjb** [comment]
sorry for the Long delay. I was sick for some days.
The workaround with the tempfile ist working now so I think this is an issue with vbscript and escaping special characters

Regards
Joachim
